base: &base
  adapter: postgresql
  pool: 200
  database: infracity_development
  username: rpx_service
  password: rpx_service-qa
  host: localhost

development:
  <<: *base

production:
  <<: *base

test:
  <<: *base
  database: infracity_test
