base: &base
  adapter: postgresql
  pool: 200
  database: infracity_development
  username: <%= ENV['DB_USER'] || 'rpx_service' %>
  password: <%= ENV['DB_PASS'] || 'rpx_service-qa' %>
  host: localhost

development:
  <<: *base

production:
  <<: *base

test:
  <<: *base
  database: infracity_test
