base: &base
  adapter: postgresql
  pool: 200
  database: infracity_development
  username: portal
  password: portal
  host: localhost

development:
  <<: *base

production:
  <<: *base

test:
  <<: *base
  database: infracity_test
